# OpenSearch host and IRSA ARN are dynamically
# updated during provisioning process
# See https://github.com/resmoio/kubernetes-event-exporter and
# https://artifacthub.io/packages/helm/bitnami/kubernetes-event-exporter
# for full set of options
#
# Enable OpenSearch as a sink
#
# deDot is set to true to avoid mapper errors
# See https://github.com/resmoio/kubernetes-event-exporter/issues/20
# See https://github.com/aws-observability/aws-sigv4-proxy-admission-controller
# See 
---
config:
  logLevel: debug
  logFormat: json
  # To address client-side throttling errors
  kubeQPS: 100
  kubeBurst: 500
  # Increase maxEventsAgeSeconds for demo purposes
  # Allows capture of all events in the last hour
  maxEventsAgeSeconds: 3600
  route:
    routes:
      - match:
          - receiver: opensearch-receiver
  receivers:
    - name: "opensearch-receiver"
      opensearch:
        index: eks-kubernetes-events
        indexFormat: "eks-kubernetes-events"
        # Setting useEventID enables update to same
        # OpenSearch document using uid from Kubernetes event
        useEventID: true
        # Dots in labels and annotation keys are replaced by underscores.
        deDot: true
        hosts:
          - http://localhost:9000

sidecars:
  - name: aws-sigv4-proxy-sidecar
    image: public.ecr.aws/aws-observability/aws-sigv4-proxy:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 9000    
    args:
      - --host
      - aaa
      - --port
      - :9000
      - --region
      - bbbb
      - --name
      - aoss
      - -v

serviceAccount:
  name: events-aoss
  create: true
  automountServiceAccountToken: true  
  annotations:
    "eks.amazonaws.com/role-arn": ccc